### ISSUE TITLE
Poor IE11 support due to using CSS variables

### ISSUE THREAD

**Issue by PixievoltNo1** [papeloto/modaly.js#7]
This project claims IE11 support in its readme, but due to using CSS variables, it will not animate or show its background.

**Comment by vimtor** [comment]
Hi there! Thanks for notifying the issue. Currently, I removed the support for IE11 from the browser list link.

I will try to solve it, but the solution I've found relies on using polyfills which will make the package size significantly bigger. If you come up with a better solution please let me know!
